-- Table: FactProductRecommendation
-- Stores personalized product recommendations for users, generated by ML models.

CREATE TABLE IF NOT EXISTS `price-pulse-470211.warehouse.FactProductRecommendation` (
  recommendation_id INT64 NOT NULL,                 -- Surrogate key for the recommendation record
  user_id INT64 NOT NULL,                           -- ID of the user (from the User Database, external reference)
  recommended_variant_id INT64 NOT NULL,            -- References DimVariant.variant_id (not enforced)
  model_id INT64 NOT NULL,                          -- References DimModel.model_id (not enforced)
  recommendation_score FLOAT64,                     -- ML model's relevance score for the recommendation
  recommendation_type STRING,                       -- Type of recommendation (e.g., 'collaborative', 'content-based')
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP    -- Timestamp when the recommendation was created
)
OPTIONS(
  description="Fact table for ML-generated personalized product recommendations for users."
);

-- Note: BigQuery does not enforce primary or foreign key constraints.
-- user_id, recommended_variant_id, and model_id should reference their respective tables, but this is not enforced.